name: cross_connectivity
version: 1.1.0
homepage: https://github.com/marchdev-tk/cross_connectivity
description: A Flutter plugin for handling Connectivity and REAL Connection state in the mobile, web and desktop platforms. Supports iOS, Android, Web, Windows, Linux and macOS.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.8
  http: ^0.12.1
  rxdart: ^0.24.1
  simple_connectivity: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
